### PR TITLE
improve card ui on home page

### PR DESCRIPTION
**Pull request by akaka0039**

### CODE REVIEW

**Comment by akaka0039** [comment]
android
Screenshot_1679460838

**Comment by akaka0039** [comment]
iOS 
https://user-images.githubusercontent.com/40246308/226806700-5aea9d88-d2a2-4aa3-ae1e-9b307efd5ef9.MOV

**Comment by akaka0039** [comment]
ios
Screenshot_1679460838

**Review by j3rryzh — COMMENTED** [review]
- I think we need to add the `Your Progress` card between the greeting and the Challenge cards in this final version.
- The clock icon with `coming soon` text can be deleted according to the UI draft.
- The greeting on home page should be changed by time.

**Review by huishi329 — APPROVED** [review]
Awesome work Eric!

**Review by j3rryzh — APPROVED** [review]

**Pull request merged**
