### PR TITLE
create new finish page of ui

### PR DESCRIPTION
**Pull request by akaka0039**

### CODE REVIEW

**Comment by akaka0039** [comment]
android(Pixel_4)
Screenshot_1679381079

**Comment by akaka0039** [comment]
Android(Pixel_4)
Screenshot_1679381919

**Comment by akaka0039** [comment]
ios(iPhone 8)
image

**Comment by akaka0039** [comment]
https://user-images.githubusercontent.com/40246308/226537972-ec7c223a-600c-4236-bcab-3655f9d3522e.MOV

**Review by huishi329 — APPROVED** [review]

**Pull request merged**
